ARG version
FROM almalinux:${version:-8}
#IF WE DON'T GIVE IT WILL TAKE DEAFULT ONE I,E IS 8 SUPPOSE IF WE GIVE SOMETHING LIKE 9 THEN IT WILL TAKE 9'
ARG COURSE="Docker" \
    TRAINER="Sivakumar" \
    DURATION="10HRS" \
    AUTHOR="joindevops"
RUN echo "Trainer is: ${TRAINER}
CMD ["sleep", "200"]